
name: 'Run ESLint and upload results'
description: 'Runs eslint and uploads results to GitHub Advanced Security'
inputs:
  src-dir:  # id of input
    description: 'The base directory of the source code'
    required: true
    default: '.'
  eslint-opts:  # id of input
    description: 'Options to pass to the eslint command line'
    required: false
    default: ''
  sarif-category:  # id of input
    description: 'Used to distinguish between multiple analyses performed on different parts of the code. e.g. apps in a monorepo'
    required: false
    default: ''
  github-token:
    description: 'The token used to access the repo and write the security results.  Defaults to GITHUB_TOKEN.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src-dir }}
    - ${{ inputs.eslint-opts }}
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GITHUB_RUN_ID: ${{ github.run_id }}
    SARIF_CATEGORY: ${{ sarif-category }}