# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and publish ESLint image

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version Bump Type (m)ajor, m(i)nor, (p)atch"
        required: true
        default: "p"
      release_description:
        description: "Release notes"
        required: true
        default: "enter  notes"

jobs:
  release-build-docker:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Set ENV from VERSION
        run: |
          cat ./docker-eslint-sarif/VERSION >> $GITHUB_ENV

      - name: Display ENV parameters
        run: |
          echo "::debug::Bump Type: ${{ github.event.inputs.version_type }}"
          echo "::debug::Version: ${{ env.VERSION }}"

      - name: Simple Semver
        id: semver
        uses: matt-FFFFFF/simple-semver@v0.1.0
        with:
          semver-input: ${{ env.VERSION }}
          increment: ${{ github.event.inputs.version_type }}

      - name: New version is ${{ steps.semver.outputs.semver }}
        run: echo "::debug::New version is ${{ steps.semver.outputs.semver }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker-eslint-sarif/.
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-eslint-sarif:latest
            ghcr.io/${{ github.repository_owner }}/docker-eslint-sarif:${{ steps.semver.outputs.semver }}
            
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.semver }}
          release_name: docker-eslint-sarif ${{ steps.semver.outputs.semver }}
          body: ${{ github.event.inputs.release_description }}
          draft: false
          prerelease: false

      - name: Save new VERSION
        run: echo VERSION=${{ steps.semver.outputs.semver }} >./docker-eslint-sarif/VERSION

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: the Dave
          author_email: dave@digitalnoise.net
          message: "Bump release version in VERSION file to ${{ steps.semver.outputs.semver }}"
          cwd: ${{ env.PROJECT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
